AWS - SSL Documentation
WolframResearch/WAS-Kubernetes pull request #19
Opened 2022-05-25 15:50 UTC by cenkawolfram

The documentation is added for SSL support for WAS domains.

It uses cert-manager&let's encrypt to create and renew certificates automatically.

2022-06-08 19:08 UTC, delaix requested changes

2022-06-08 19:08 UTC, delaix commented on EnvironmentSetup/General/SSL.md
> +* Needed the Kubernetes command-line tool, [kubect](https://kubernetes.io/docs/tasks/tools/)
Strike the word 'Needed'

2022-06-08 19:08 UTC, delaix commented on EnvironmentSetup/General/SSL.md
> +  - To enable HTTPS on your website, you need to get a certificate (a type of file) from a Certificate Authority (CA). Let’s Encrypt is a CA.In order to get a certificate for your website’s domain fr
CA.In --> CA. In

2022-06-15 14:33 UTC, cenkawolfram commented
I just updated the title.

2022-06-21 17:14 UTC, manjuchandrika approved these changes

2022-06-21 21:29 UTC, merged